imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

swiftmailer:
    transport: "%mailer_transport%"
    encryption: "%mailer_encryption%"
    auth_mode: "%mailer_auth_mode%"
    host:      "%mailer_host%"
    username:  "%mailer_username%"
    password:  "%mailer_password%"

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Ens\LunchBundle\Entity\User

fr3d_ldap:
    driver:
        host:                tps.local
        port:                389
        username:            Барышев Дмитрий анатольевич
        password:            tanya220964
        accountFilterFormat: (&(samaccountname=%s))
    user:
        baseDn: DC=tps,DC=local
        filter: (&(ObjectClass=Person))
        attributes:

           - { ldap_attr: samaccountname,  user_method: setusername }
           - { ldap_attr: name,  user_method: setUsernameCanonical }
           - { ldap_attr: cn,  user_method: setName }
           - { ldap_attr: mail,  user_method: setEmail }

    service:
       user_manager: ens_lunch.user_manager
       ldap_manager: ens_lunch.ldap_manager

parameters:
    upload_path:
      documents: /documents
      orders: /orders

