#ens_file_upload:
#    resource: "@EnsFileUploadBundle/Resources/config/routing.yml"
#    prefix:   /

EnsLunchBundle_lunch:
        resource: "@EnsLunchBundle/Resources/config/routing/lunch.yml"
        prefix:   /lunch

ens_lunch:
    resource: "@EnsLunchBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
