#security:
##    hide_user_not_found: false
#    encoders:
#        FOS\UserBundle\Model\UserInterface: sha512
#        IMAG\LdapBundle\User\LdapUser: plaintext
#
#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: ROLE_ADMIN
#
#    providers:
##        fos_userbundle:
##            id: fos_user.user_provider.username
#        ldap:
#            id: imag_ldap.security.user.provider
#
#    firewalls:
#        main:
#            pattern: ^/
#            form_login:
#                provider: ldap
#                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
#            logout:       true
#            anonymous:    true
#
#        login:
#            pattern: ^/login$
#            logout:       true
#            anonymous:    ~
#
#        restricted_area:
#              pattern:          ^/
#              anonymous:        ~
#              provider:         ldap
#              imag_ldap:        ~
#              # alternative configuration
#              # imag_ldap:
#              #   login_path:   /ninja/login
#              logout:
#                path:           /logout
#                target:         /
#
#
#    access_control:
#        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/, role: ROLE_ADMIN }
##        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
##
#imag_ldap:
#      client:
#        host: tps.local
#        port: 389
#        username: tps\d.baryshev
#        password: tanya220964
#        referrals_enabled: false
#        bind_username_before: false
#        skip_roles: true
#
#      user:
#
#        base_dn: OU=Users,OU=R4S,OU=SVRD-44-B,OU=SPB,OU=RU,OU=Offices,DC=tps,DC=local
    #    filter: (&(foo=bar)(ObjectClass=Person)) #Optional
#        name_attribute: uid
#      role:
#       base_dn: OU=Group,DC=tps,DC=local
#
##    #    filter: (ou=group) #Optional
#       name_attribute: cn
#       user_attribute: member
#       user_id: d.baryshev@tps.local

security:
#    hide_user_not_found: false
    encoders:
        Ens\LunchBundle\Entity\User: plaintext

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, fr3d_ldapbundle]

        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider

        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            fr3d_ldap:  ~
            form_login:
#                provider: fos_userbundle
#                csrf_provider: form.csrf_provider
                always_use_default_target_path: true
                default_target_path: /profile
                provider: chain_provider
#                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:       true
            anonymous:    true
        default:
            anonymous: ~
