security:
#    hide_user_not_found: false
    encoders:
        FOS\UserBundle\Model\User: sha512

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, fr3d_ldapbundle]

        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider

        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        main:
            pattern: ^/
            fr3d_ldap:  ~
            form_login:
                always_use_default_target_path: true
                default_target_path: /
#                csrf_provider: form.csrf_provider
#                provider: fos_userbundle
#                provider: chain_provider
#                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:       true
            anonymous:    true
        default:
            anonymous: ~
