security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        IMAG\LdapBundle\User\LdapUser: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
#        ldap:
#            id: imag_ldap.security.user.provider

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:       true
            anonymous:    true

        login:
            pattern: ^/login$
            logout:       true
            anonymous:    ~

#        restricted_area:
#              pattern:          ^/
#              anonymous:        ~
#              provider:         ldap
#              imag_ldap:        ~
#              # alternative configuration
#              # imag_ldap:
#              #   login_path:   /ninja/login
#              logout:
#                path:           /logout
#                target:         /


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
#        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
#
#imag_ldap:
#      client:
#        host: tps.local
#        port: 389
#
#      user:
#        base_dn: ou=people,dc=host,dc=foo
#    #    filter: (&(foo=bar)(ObjectClass=Person)) #Optional
#        name_attribute: uid
##      role:
##        base_dn: ou=group, dc=host, dc=foo
##    #    filter: (ou=group) #Optional
##        name_attribute: cn
##        user_attribute: member
##        user_id: d.baryshev
