# src/Ens/LunchBundle/Resources/config/doctrine/lunch.orm.yml
Ens\LunchBundle\Entity\Lunch:
    type: entity
    repositoryClass: Ens\LunchBundle\Repository\LunchRepository
    table: lunch
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        categories:
            type: string
            length: 255
            nullable: true
        day:
            type: string
            length: 255
            nullable: true
        active:
            type: boolean
            nullable: true
        count:
            type: integer
            nullable: true
        description:
            type: string
            length: 255
            nullable: true
        created_at:
            type: datetime
            nullable: true
        updated_at:
            type: datetime
            nullable: true
    manyToMany:
        user:
            targetEntity: Ens\LunchBundle\Entity\User
    joinTable:
            name: users_lunches
            joinColumns:
                      name: lunch_id
                      referencedColumnName: id
            inverseJoinColumns:
                      joinColumn:
                      name: user_id
                      referencedColumnName: id


#    manyToOne:
#        day:
#            targetEntity: Day
#            inversedBy: lunches
#            joinColumn:
#                name: day_id
#                referencedColumnName: id

    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]
        prePersist: [ preUpload, setCreatedAtValue, setExpiresAtValue ]
        preUpdate: [ preUpload, setUpdatedAtValue ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]