# src/Ens/LunchBundle/Resources/config/doctrine/lunch.orm.yml
Ens\LunchBundle\Entity\Lunch:
    type: entity
    repositoryClass: Ens\LunchBundle\Repository\LunchRepository
    table: lunch
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        categories:
            type: string
            length: 255
        day:
            type: string
            length: 255
        count:
            type: integer
        description:
            type: string
            length: 255
        created_at:
            type: datetime
        updated_at:
            type: datetime
            nullable: true
#    manyToOne:
#        person:
#            targetEntity: Person
#            inversedBy: lunches
#            joinColumn:
#                name: person_id
#                referencedColumnName: id
#    manyToOne:
#        day:
#            targetEntity: Day
#            inversedBy: lunches
#            joinColumn:
#                name: day_id
#                referencedColumnName: id

    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]
        prePersist: [ preUpload, setCreatedAtValue, setExpiresAtValue ]
        preUpdate: [ preUpload, setUpdatedAtValue ]
        postPersist: [ upload ]
        postUpdate: [ upload ]
        postRemove: [ removeUpload ]