# src/Ens/LunchBundle/Resources/config/doctrine/Person.orm.yml
Ens\LunchBundle\Entity\Person:
    type: entity
    repositoryClass: Ens\LunchBundle\Repository\CategoryRepository
    table: category
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            unique: true
    oneToMany:
        lunches:
            targetEntity: Lunch
            mappedBy: person