EnsLunchBundle_lunch:
    resource: "@EnsLunchBundle/Resources/config/routing/lunch.yml"
    prefix:   /

EnsLunchBundle_homepage:
        pattern:  /
        defaults: { _controller: EnsLunchBundle:Lunch:index}
