ens_lunch:
    path:     /
    defaults: { _controller: "EnsLunchBundle:Lunch:index" }
    methods:  GET

ens_lunch_admin:
    path:     /admin
    defaults: { _controller: "EnsLunchBundle:Lunch:adminIndex" }
    methods:  GET

ens_lunch_show:
    path:     /admin/{id}/show
    defaults: { _controller: "EnsLunchBundle:Lunch:show" }

ens_lunch_upload:
    path:     /admin/upload
    defaults: { _controller: "EnsLunchBundle:Lunch:upload" }


ens_lunch_create:
    path:     /admin/creating
    defaults: { _controller: "EnsLunchBundle:Lunch:create" }


ens_lunch_edit:
    path:     /admin/{id}/edit
    defaults: { _controller: "EnsLunchBundle:Lunch:edit" }

ens_lunch_update:
    path:     /admin/{id}/update
    defaults: { _controller: "EnsLunchBundle:Lunch:update" }
    methods:  [POST, PUT]

ens_lunch_delete:
    path:     /admin/{id}/delete
    defaults: { _controller: "EnsLunchBundle:Lunch:delete" }
    methods:  [POST, DELETE]

ens_lunch_show_all:
    path:     /admin/all
    defaults: { _controller: "EnsLunchBundle:Lunch:showAll" }
    methods:  GET

ens_lunch_order:
    path:     /order
    defaults: { _controller: "EnsLunchBundle:Lunch:order" }
    methods:  POST

ens_all_users:
    path:     /admin/users
    defaults: { _controller: "EnsLunchBundle:Lunch:showAllUsers" }
    methods:  GET

ens_all_docs:
    path:     /admin/files
    defaults: { _controller: "EnsLunchBundle:Lunch:showAllDocs" }
    methods:  GET
