ens_lunch:
    path:     /
    defaults: { _controller: "EnsLunchBundle:Lunch:index" }
    methods:  GET

ens_lunch_admin:
    path:     /admin
    defaults: { _controller: "EnsLunchBundle:Admin:adminIndex" }
    methods:  GET

ens_lunch_show:
    path:     /admin/{id}/show
    defaults: { _controller: "EnsLunchBundle:Admin:show:show" }

ens_lunch_upload:
    path:     /admin/upload
    defaults: { _controller: "EnsLunchBundle:Admin:upload" }

ens_lunch_upload_order:
    path:     /admin/upload_order
    defaults: { _controller: "EnsLunchBundle:Admin:uploadOrder" }

ens_lunch_edit:
    path:     /admin/{id}/edit
    defaults: { _controller: "EnsLunchBundle:Admin:edit" }

ens_lunch_update:
    path:     /admin/{id}/update
    defaults: { _controller: "EnsLunchBundle:Admin:update" }
    methods:  [POST, PUT]

ens_lunch_delete:
    path:     /admin/{id}/delete
    defaults: { _controller: "EnsLunchBundle:Admin:delete" }
    methods:  [POST, DELETE]

ens_lunch_show_all:
    path:     /admin/all
    defaults: { _controller: "EnsLunchBundle:Admin:showAll" }
    methods:  GET

ens_lunch_order:
    path:     /order
    defaults: { _controller: "EnsLunchBundle:Admin:order" }
    methods:  POST

ens_all_users:
    path:     /admin/users
    defaults: { _controller: "EnsLunchBundle:Admin:showAllUsers" }
    methods:  GET

ens_all_docs:
    path:     /admin/files
    defaults: { _controller: "EnsLunchBundle:Admin:showAllDocs" }
    methods:  GET

ens_download_menu:
    path:     /admin/download_menu
    defaults: { _controller: "EnsLunchBundle:Admin:downloadMenuFile" }
    methods:  GET

ens_download_order:
    path:     /admin/download_order
    defaults: { _controller: "EnsLunchBundle:Admin:downloadOrderFile" }
    methods:  GET
