ens_lunch:
    path:     /
    defaults: { _controller: "EnsLunchBundle:Lunch:index" }
    methods:  POST

ens_lunch_admin:
    path:     /admin
    defaults: { _controller: "EnsLunchBundle:Admin:adminIndex" }
    methods:  GET

ens_lunch_profile:
    path:     /user_profile
    defaults: { _controller: "EnsLunchBundle:Admin:profile" }

ens_lunch_show:
    path:     /admin/{id}/show
    defaults: { _controller: "EnsLunchBundle:Admin:show:show" }

ens_lunch_upload:
    path:     /admin/upload
    defaults: { _controller: "EnsLunchBundle:Admin:upload" }

ens_lunch_show_all:
    path:     /admin/all
    defaults: { _controller: "EnsLunchBundle:Admin:showAll" }
    methods:  GET

ens_lunch_order:
    path:     /order
    defaults: { _controller: "EnsLunchBundle:Lunch:order" }
    methods:  POST

ens_lunch_my_order:
    path:     /my_order
    defaults: { _controller: "EnsLunchBundle:Lunch:userOrder" }
    methods:  GET


ens_all_users:
    path:     /admin/users
    defaults: { _controller: "EnsLunchBundle:Admin:showAllUsers" }
    methods:  GET

ens_order_menu_files:
    path:     /admin/files
    defaults: { _controller: "EnsLunchBundle:Admin:generateFiles" }
    methods:  POST

ens_download:
    path:     /admin/download/{name}
    defaults: { _controller: "EnsLunchBundle:Admin:downloadFile" }
    methods:  GET