<?php

namespace Ens\LunchBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Jointable
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Jointable extends EntityRepository
{
    public function getActiveJoinsOrderedByUsers()
    {
        $qb = $this->createQueryBuilder('j');

        $qb->where('j.active = :isActive')
            ->setParameter('isActive', true)
            ->orderBy('j.id_user');

        $query = $qb->getQuery();

        return $query->getResult();
    }

    public function getPastUserJoins($id)
    {
        $qb = $this->createQueryBuilder('j');

        $qb->where('j.id_user = :idUser')
            ->setParameter('idUser', $id);

        $query = $qb->getQuery();

        return $query->getResult();
    }
}
