<?php

namespace Ens\LunchBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LunchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LunchRepository extends EntityRepository
{
    public function getDaysLunch($category_id = null)
    {
        $qb = $this->createQueryBuilder('l')
            ->where('l.day_of_week = :day')
            ->setParameter('day', "friday")
            ->orderBy('l.description');

        if($category_id)
        {
            $qb->andWhere('l.category = :category_id')
                ->setParameter('category_id', $category_id);
        }

        $query = $qb->getQuery();

        return $query->getResult();
    }

}
