<?php

namespace Ens\LunchBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LunchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LunchRepository extends EntityRepository
{
    public function getCategoryDayLunches()
    {
        $query = $this->getEntityManager()->createQuery(
            'SELECT c FROM EnsLunchBundle:Lunch c ORDER BY FIELD(c.day, "Monday", "Tuesday"   ) '
        );

        return $query->getResult();

    }

}